### ISSUE TITLE
Plugin crashes verdaccio

### ISSUE THREAD

**Issue by smelukov** [Alexandre-io/verdaccio-ldap#39]
Sometimes verdaccio crashes with error
```
Error: getaddrinfo EMFILE ldap-server:636
    at Object._errnoException (util.js:992:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

`ulimit -n` is 4096

**Comment by kopax** [comment]
Hi @smelukov , the problem is that the module doesn't keep in cache the connection. There is a way to cache the authentication so it doesn't need to reauthenticate.

verdaccio-gitlab was having the same problem and they solved it here: 

https://github.com/bufferoverflow/verdaccio-gitlab/pull/23

If you are willing to implement nodeCache, pr are welcome. It should take about 1h.

related issues:

- https://github.com/bufferoverflow/verdaccio-gitlab/issues/13
- #37

**Comment by Alexandre-io** [comment]
@smelukov the error seems to be related to an dns resolution issue. Consider to install `nscd` and activate ldap cache:
```
auth:
  ldap:
    type: ldap
    client_options:
      cache: true
```

**Comment by kopax** [comment]
@Alexandre-io where is the `cache` option documented and is this what you were referring to be used instead of `node-cache`?

**Comment by tiandrey** [comment]
@kopax, the problem is that connection to the LDAP server is not closed after authentication, and each authentication request opens new connection - the longer verdaccio works, the more connections are open. For example: our verdaccio installation is running for 2 hours, and it has already established 952 connections to the LDAP server; the number is rising as I write this comment. I guess all we need to do is close connection to the LDAP server after authentication (I'm not a NodeJS programmer, so can't help with that :disappointed:)

@Alexandre-io, DNS resolution has nothing to do with the error - EMFILE error means that verdaccio couldn't open new network connection because of number of open file descriptors has reached the limit.

**Comment by kopax** [comment]
@tiandrey have you look at https://github.com/Alexandre-io/verdaccio-ldap/pull/40 I have implemented `node-cache`, also it seems there is already a way to cash your connection using : 

```bash
auth:
  ldap:
    type: ldap
    client_options:
      cache: true # <---- this
```

[Because under the hood it use a library](https://github.com/Alexandre-io/verdaccio-ldap/pull/40#issuecomment-407383505) that already as [caching](https://github.com/vesse/node-ldapauth-fork#ldapauth-config-options) , it is possible that my merge request is solving something already resolved and that you can solve it yourself with it.

Let me know if you can test it as I have never tried the `cache` option of `node-ldapauth-fork`. My question was directly addressed to @Alexandre-io because after a few week of questions and non answers, I decided to do my PR and it got refused because of that.

**Comment by Alexandre-io** [comment]
@tiandrey my bad, this should be fixed with the latest version (3.0.0).

**Comment by tiandrey** [comment]
@Alexandre-io, thanks, fix seems to work (I did not enable cache)!

**Comment by kopax** [comment]
Is the cache fixed now?
